version: 0.0
os: linux
files:
  - source: /
    destination: /root/kokonut_api_guide/
permissions:
  - object: /root/kokonut_api_guide/
    pattern: "**"
    owner: root
    group: root
hooks:
  AfterInstall:
    - location: script/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: root
      